/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.firebaseconexion;

/*import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.CollectionReference;
import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;*/
import java.awt.Toolkit;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
//import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martin
 */
public class JFrame extends javax.swing.JFrame {

   // DefaultTableModel laTabla;

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();

        //laTabla = (DefaultTableModel) tabla.getModel();
        try {
            FirebaseConexion.conectar();
        } catch (IOException e) {
            System.out.print("no inició: " + e);

        }
        //cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        receta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        ingredientes = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(208, 171, 111));

        jPanel4.setBackground(new java.awt.Color(208, 171, 111));

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(176, 116, 45), new java.awt.Color(176, 116, 45)));

        jPanel2.setBackground(new java.awt.Color(248, 255, 209));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(176, 116, 45), new java.awt.Color(176, 116, 45)));

        jButton1.setBackground(new java.awt.Color(245, 239, 234));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(208, 171, 111));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(176, 116, 45), new java.awt.Color(176, 116, 45)));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cupcake-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(208, 171, 111));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(176, 116, 45), new java.awt.Color(176, 116, 45)));

        jPanel1.setBackground(new java.awt.Color(248, 255, 209));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(176, 116, 45), new java.awt.Color(176, 116, 45)));

        receta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                recetaKeyTyped(evt);
            }
        });

        jLabel1.setText("Receta");

        jLabel2.setText("Nombre de la receta");

        jLabel3.setText("Pais");

        jLabel4.setText("Ingredientes");

        jLabel5.setText("Dulce o Salado");

        nombre.setAlignmentX(1.0F);
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });

        pais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paisKeyTyped(evt);
            }
        });

        ingredientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingredientesKeyTyped(evt);
            }
        });

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dulce", "Salado" }));
        tipo.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombre)
                    .addComponent(pais)
                    .addComponent(ingredientes)
                    .addComponent(receta, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Nombre, Pais, Ingredientes, Tipo, Receta;
        Nombre = nombre.getText();
        Pais = pais.getText();
        Ingredientes = ingredientes.getText();
        Tipo = tipo.getSelectedItem().toString();
        Receta = receta.getText();
        Map<String, Object> datosJson = new HashMap<>();
        datosJson.put("receta", Receta);
        datosJson.put("nombre", Nombre);
        datosJson.put("ingredientes", Ingredientes);
        datosJson.put("tipo", Tipo);
        datosJson.put("pais", Pais);
        FirebaseConexion.metemeDatos(Pais, Nombre,datosJson);
        //cargarDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        //SOLO PERMITEN LETRAS MAYUSUCLAS Y MINUSCULAS
        if (evt.getKeyChar()>64 && evt.getKeyChar()<89 ){
    
    }else if (evt.getKeyChar()<123 && evt.getKeyChar()>96 ){
    
    }else if (evt.getKeyChar()<163 && evt.getKeyChar()>166 ){
    
    }else if (evt.getKeyChar() == 8){
    
    }else if (evt.getKeyChar() == 32){
    
    //en caso de que se ingrese una tecla no deseada sonara un beep y mostrara un mensaje de advertencia ademas que no permitira ingresar esa tecla    
    }else{
    JOptionPane.showMessageDialog(null, "no se permiten numeros ni simbolos");
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
       
    }                             
        //DA UN MAXIMO DE TAMAÑO
     if(nombre.getText().length() >= 30)
    {
        evt.consume();
    }
    
        
    }//GEN-LAST:event_nombreKeyTyped

    private void paisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paisKeyTyped
        //SOLO PERMITEN LETRAS MAYUSUCLAS Y MINUSCULAS
        if (evt.getKeyChar()>64 && evt.getKeyChar()<89 ){
    
    }else if (evt.getKeyChar()<123 && evt.getKeyChar()>96 ){
    
    }else if (evt.getKeyChar()<163 && evt.getKeyChar()>166 ){
    
    }else if (evt.getKeyChar() == 8){
    
    }else if (evt.getKeyChar() == 32){
    
    //en caso de que se ingrese una tecla no deseada sonara un beep y mostrara un mensaje de advertencia ademas que no permitira ingresar esa tecla    
    }else{
    JOptionPane.showMessageDialog(null, "no se permiten numeros ni simbolos");
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
       
    }                             
        //DA UN MAXIMO DE TAMAÑO
     if(pais.getText().length() >= 30)
    {
        evt.consume();
    }
    }//GEN-LAST:event_paisKeyTyped

    private void ingredientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingredientesKeyTyped
        //SOLO PERMITEN LETRAS MAYUSUCLAS Y MINUSCULAS
        if (evt.getKeyChar()>64 && evt.getKeyChar()<89 ){
    
    }else if (evt.getKeyChar()<123 && evt.getKeyChar()>96 ){
    
    }else if (evt.getKeyChar()<163 && evt.getKeyChar()>166 ){
    
        //PERMITE LOS NUMEROS TAMBIEN
    }else if (evt.getKeyChar()<58 && evt.getKeyChar()>47 ){
    
    }else if (evt.getKeyChar() == 8){
    
    }else if (evt.getKeyChar() == 32){
    
    //en caso de que se ingrese una tecla no deseada sonara un beep y mostrara un mensaje de advertencia ademas que no permitira ingresar esa tecla    
    }else{
    JOptionPane.showMessageDialog(null, "no se permiten numeros ni simbolos");
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
       
    }                             
        //DA UN MAXIMO DE TAMAÑO
     if(ingredientes.getText().length() >= 300)
    {
        evt.consume();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientesKeyTyped

    private void recetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recetaKeyTyped
        //SOLO PERMITEN LETRAS MAYUSUCLAS Y MINUSCULAS
        if (evt.getKeyChar()>64 && evt.getKeyChar()<89 ){
    
    }else if (evt.getKeyChar()<123 && evt.getKeyChar()>96 ){
    
    }else if (evt.getKeyChar()<163 && evt.getKeyChar()>166 ){
    
    }else if (evt.getKeyChar() == 8){
    
    }else if (evt.getKeyChar() == 32){
    
    //en caso de que se ingrese una tecla no deseada sonara un beep y mostrara un mensaje de advertencia ademas que no permitira ingresar esa tecla    
    }else{
    JOptionPane.showMessageDialog(null, "no se permiten numeros ni simbolos");
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
       
    }                             
        //DA UN MAXIMO DE TAMAÑO
     if(receta.getText().length() >= 600)
    {
        evt.consume();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_recetaKeyTyped

   /* private void cargarDatos() {
        String Pais = pais.getText();
        //String  Nombre = nombre.getText();
        CollectionReference paises = FirebaseConexion.bd.collection(Pais);
        ApiFuture<QuerySnapshot> laQuery = paises.get();
        int filas = laTabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            laTabla.removeRow(0);
        }
        try {
            for (DocumentSnapshot documento : laQuery.get().getDocuments()) {
                System.out.println(documento.getId());
                laTabla.addRow(new Object[]{documento.getString("receta")
                });
                System.out.println("ID" + documento.getId() + "Argentina:" +documento.getString("Argentina") + "recetas:" +documento.getString("recetas") );

}
} catch (InterruptedException | ExecutionException ex) {
            System.out.print("falló actualizar " + ex);
        }
    }*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /*Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        }); 
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ingredientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pais;
    private javax.swing.JTextField receta;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
